import type { CSSProperties } from 'react';

export const appShellStyles: Record<string, CSSProperties> = {
    appShell: {
        display: 'flex',
        height: '100vh',
        width: '100vw',
        overflow: 'hidden',
    },
    mainContent: {
        flex: 1,
        overflowY: 'auto',
        padding: 0,
        position: 'relative',
        height: '100vh',
    },
    loading: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 16,
        height: '60vh',
    },
    loadingText: {
        color: 'var(--text-secondary)',
        fontFamily: 'var(--font-mono)',
        fontSize: 14,
    },
    backBtnLoading: {
        background: 'var(--teakwood)',
        border: '1px solid var(--teakwood)',
        color: 'var(--autumn-cream)',
        fontSize: 14,
        cursor: 'pointer',
        padding: '6px 14px',
        borderRadius: 4,
        fontFamily: 'var(--font-mono)',
    },
    settingsCog: {
        position: 'fixed',
        bottom: 12,
        right: 12,
        zIndex: 8000,
        background: 'var(--bg-card)',
        border: '1px solid var(--border)',
        borderRadius: '50%',
        width: 36,
        height: 36,
        fontSize: 20,
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'var(--text-secondary)',
        boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
        transition: 'transform 0.3s',
    },
};
