import type { CSSProperties } from 'react';

export const simpleFloorLayoutStyles: Record<string, CSSProperties> = {
    container: {
        display: 'flex',
        flexDirection: 'column',
        minHeight: '100vh',
        background: 'var(--bg-primary)',
        padding: '20px 24px',
        fontFamily: 'var(--font-sans)',
        transition: 'background-color 0.3s ease, color 0.3s ease',
    },
    header: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingBottom: 16,
        borderBottom: '1px solid var(--border)',
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 700,
        color: 'var(--text-primary)',
        lineHeight: 1.2,
        margin: 0,
    },
    headerSubtitle: {
        fontSize: 12,
        fontWeight: 500,
        color: 'var(--text-tertiary)',
        fontFamily: 'var(--font-mono)',
        margin: '4px 0 0',
    },
    headerActions: {
        display: 'flex',
        gap: 8,
        alignItems: 'center',
    },
    headerOwnerCluster: {
        display: 'flex',
        alignItems: 'center',
        gap: 10,
        flexWrap: 'wrap' as const,
    },
    globalStepHeaderBtn: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        padding: '8px 12px',
        borderRadius: 6,
        border: '1px solid var(--border)',
        background: 'var(--bg-secondary)',
        cursor: 'pointer',
        fontFamily: 'inherit',
        color: 'inherit',
    },
    secondaryLink: {
        padding: '8px 12px',
        borderRadius: 6,
        border: '1px solid var(--border)',
        background: 'var(--bg-secondary)',
        color: 'var(--accent)',
        fontFamily: 'var(--font-mono)',
        fontSize: 13,
        fontWeight: 600,
        textDecoration: 'none',
        whiteSpace: 'nowrap',
    },
    iconBtn: {
        background: 'var(--bg-card)',
        border: '1px solid var(--border)',
        borderRadius: '50%',
        width: 36,
        height: 36,
        fontSize: 18,
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'var(--text-secondary)',
        position: 'relative' as const,
    },
    themeToggleBtn: {
        background: 'var(--bg-card)',
        border: '1px solid var(--border)',
        borderRadius: '50%',
        width: 34,
        height: 34,
        padding: 0,
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        color: 'var(--text-secondary)',
        transition: 'background-color 0.3s ease, color 0.3s ease, border-color 0.3s ease, box-shadow 0.3s ease',
        flexShrink: 0,
    },
    badge: {
        position: 'absolute' as const,
        top: -4,
        right: -4,
        background: 'var(--error)',
        color: '#fff',
        fontSize: 12,
        fontWeight: 700,
        borderRadius: '50%',
        width: 20,
        height: 20,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    statLabel: {
        fontSize: 10,
        fontWeight: 600,
        textTransform: 'uppercase' as const,
        color: 'var(--text-tertiary)',
        fontFamily: 'var(--font-mono)',
        letterSpacing: 0.5,
    },
    createStoryBtn: {
        padding: '6px 14px',
        borderRadius: 6,
        border: '1px solid var(--accent)',
        background: 'var(--accent)',
        color: '#fff',
        fontSize: 12,
        fontWeight: 600,
        fontFamily: 'var(--font-mono)',
        cursor: 'pointer',
    },
    agentGrid: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, 1fr)',
        gap: 16,
        padding: '16px 0',
    },
};
