import type { CSSProperties } from 'react';

export const agentDetailStyles: Record<string, CSSProperties> = {
    container: { display: 'flex', flexDirection: 'column', gap: 20, padding: '24px 32px', height: '100vh', overflowY: 'auto', background: 'var(--bg-primary)' },

    header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', paddingBottom: 16, borderBottom: '2px solid var(--teakwood)' },
    headerLeft: { display: 'flex', alignItems: 'center', gap: 12 },
    headerRight: { display: 'flex', alignItems: 'center', gap: 12 },
    backBtn: {
        background: 'var(--teakwood)',
        border: '1px solid var(--teakwood)',
        color: 'var(--autumn-cream)',
        fontSize: 18,
        cursor: 'pointer',
        padding: '4px 10px',
        borderRadius: 4,
        marginRight: 4,
        fontFamily: 'var(--font-sans)',
    },
    pickupBtn: {
        fontSize: 12,
        fontFamily: 'var(--font-mono)',
        padding: '5px 14px',
        borderRadius: 4,
        background: 'var(--accent-dim)',
        border: '1px solid',
        cursor: 'pointer',
        fontWeight: 700,
        letterSpacing: '0.03em',
    },
    btwBtn: {
        fontSize: 12,
        fontFamily: 'var(--font-mono)',
        padding: '5px 14px',
        borderRadius: 4,
        background: 'var(--accent-dim)',
        border: '1px solid var(--sea-turtle)',
        color: 'var(--sea-turtle)',
        cursor: 'pointer',
        fontWeight: 700,
        letterSpacing: '0.03em',
    },
    pendingBadge: {
        position: 'absolute' as const,
        top: -6,
        right: -6,
        background: 'var(--error)',
        color: '#fff',
        fontSize: 9,
        fontWeight: 800,
        fontFamily: 'var(--font-mono)',
        minWidth: 16,
        height: 16,
        borderRadius: 8,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '0 4px',
    },
    miniAvatar: {
        width: 36,
        height: 36,
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    miniAvatarLetter: { fontSize: 15, fontWeight: 800, color: '#fff' },
    title: { fontSize: 28, fontWeight: 700, letterSpacing: '-0.02em' },
    subtitle: { fontSize: 13, color: 'var(--text-tertiary)', fontFamily: 'var(--font-mono)', textTransform: 'uppercase', letterSpacing: '0.1em' },
    storyBadge: { fontFamily: 'var(--font-mono)', fontSize: 13, padding: '4px 10px', borderRadius: 4, fontWeight: 600 },
    collabBadge: {
        fontFamily: 'var(--font-mono)',
        fontSize: 11,
        padding: '3px 10px',
        borderRadius: 12,
        background: 'rgba(236, 72, 153, 0.1)',
        color: '#ec4899',
        border: '1px solid rgba(236, 72, 153, 0.3)',
        letterSpacing: '0.04em',
    },
    phaseBadge: { display: 'flex', alignItems: 'center', gap: 8, fontSize: 12, fontFamily: 'var(--font-mono)', padding: '4px 12px', borderRadius: 4, border: '1px solid', textTransform: 'uppercase', letterSpacing: '0.06em' },
    storyName: { fontSize: 14, color: 'var(--text-secondary)', marginTop: -8 },
    frontendStepCallout: {
        margin: '12px 0 0',
        padding: '14px 16px',
        borderRadius: 6,
        border: '1px solid',
        background: 'var(--bg-card)',
        maxWidth: 560,
    },
    frontendStepBadge: {
        fontSize: 10,
        fontFamily: 'var(--font-mono)',
        textTransform: 'uppercase' as const,
        letterSpacing: '0.08em',
        display: 'inline-block',
        padding: '3px 8px',
        borderRadius: 4,
        marginBottom: 8,
        fontWeight: 700,
    },
    frontendStepBody: { fontSize: 14, color: 'var(--text-secondary)', lineHeight: 1.5, margin: 0 },

    devopsWrapUpCallout: {
        margin: '16px 0 0',
        padding: '14px 16px',
        borderRadius: 8,
        border: '1px solid',
        background: 'var(--bg-card)',
        maxWidth: 640,
    },
    devopsWrapUpBadge: {
        fontSize: 10,
        fontFamily: 'var(--font-mono)',
        textTransform: 'uppercase' as const,
        letterSpacing: '0.08em',
        display: 'inline-block',
        padding: '3px 8px',
        borderRadius: 4,
        marginBottom: 8,
        fontWeight: 700,
    },
    devopsWrapUpBody: { fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.5, margin: 0 },
    taskReconciliationBanner: {
        margin: '16px 0 0',
        padding: '14px 16px',
        borderRadius: 8,
        border: '1px solid var(--warning)',
        background: 'rgba(245, 158, 11, 0.1)',
        display: 'flex',
        flexDirection: 'column' as const,
        gap: 10,
        maxWidth: 760,
    },
    taskReconciliationTitle: { margin: 0, fontSize: 13, fontFamily: 'var(--font-mono)', fontWeight: 800, color: 'var(--warning)', textTransform: 'uppercase' as const, letterSpacing: '0.06em' },
    taskReconciliationBody: { margin: 0, fontSize: 13, color: 'var(--text-secondary)', lineHeight: 1.45 },
    taskReconciliationActions: { display: 'flex', flexWrap: 'wrap' as const, gap: 10 },

    idleHero: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 20,
        padding: '60px 40px',
        textAlign: 'center',
    },
    idleAvatar: {
        width: 80,
        height: 80,
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
    },
    idleAvatarLetter: { fontSize: 36, fontWeight: 800, color: '#fff' },
    idleSummary: {
        fontSize: 15,
        color: 'var(--text-secondary)',
        maxWidth: 480,
        lineHeight: 1.6,
    },
    idleCapabilities: {
        display: 'flex',
        flexWrap: 'wrap',
        gap: 8,
        justifyContent: 'center',
    },
    idleCapBadge: {
        fontSize: 11,
        fontFamily: 'var(--font-mono)',
        padding: '4px 12px',
        borderRadius: 12,
        border: '1px solid',
        textTransform: 'uppercase',
        letterSpacing: '0.06em',
    },
    idlePickupBtn: {
        marginTop: 8,
        fontSize: 14,
        fontFamily: 'var(--font-mono)',
        fontWeight: 700,
        padding: '10px 28px',
        borderRadius: 6,
        border: 'none',
        color: '#fff',
        letterSpacing: '0.03em',
    },
    idleChatBtn: {
        fontSize: 12,
        fontFamily: 'var(--font-mono)',
        padding: '8px 20px',
        borderRadius: 6,
        background: 'transparent',
        border: '1px solid',
        cursor: 'pointer',
        fontWeight: 600,
    },

    statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(6, 1fr)', gap: 12 },
    statCard: { display: 'flex', flexDirection: 'column', gap: 2, padding: '12px 16px', background: 'var(--bg-card)', borderRadius: 6, border: '1px solid var(--border)' },
    statLabel: { fontSize: 11, fontFamily: 'var(--font-mono)', color: 'var(--text-tertiary)', textTransform: 'uppercase', letterSpacing: '0.08em' },
    statValue: { fontSize: 22, fontWeight: 700, fontFamily: 'var(--font-mono)' },
    statSub: { fontSize: 11, color: 'var(--text-tertiary)', fontFamily: 'var(--font-mono)' },

    mainGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, alignItems: 'start' },
    column: { display: 'flex', flexDirection: 'column', gap: 20 },
    section: { background: 'var(--bg-card)', borderRadius: 6, border: '1px solid var(--border)', padding: 16 },
    sectionTitle: { fontSize: 12, fontFamily: 'var(--font-mono)', color: 'var(--text-tertiary)', textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: 12 },
    emptyText: { color: 'var(--text-tertiary)', fontSize: 13, fontStyle: 'italic' },
    stepTaskScopeHint: { color: 'var(--text-secondary)', fontSize: 12, marginTop: 0, marginBottom: 10, lineHeight: 1.45 },
    reviewerPendingReviewHint: {
        margin: '0 0 16px',
        padding: '12px 14px',
        borderRadius: 6,
        border: '1px solid var(--border)',
        background: 'var(--bg-secondary)',
        fontSize: 12,
        color: 'var(--text-secondary)',
        lineHeight: 1.5,
    },
    inlinePath: { fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-primary)', wordBreak: 'break-all' as const },
    reviewerPrPanelsColumn: { display: 'flex', flexDirection: 'column' as const, gap: 16 },
    reviewerDeskPanel: {
        background: 'var(--bg-card)',
        borderRadius: 6,
        border: '1px solid var(--accent)',
        padding: 16,
        display: 'flex',
        flexDirection: 'column' as const,
        gap: 12,
        boxShadow: '0 0 0 1px rgba(99, 102, 241, 0.12)',
    },
    reviewerPickupPanel: { background: 'var(--bg-card)', borderRadius: 6, border: '1px solid var(--border)', padding: 16, display: 'flex', flexDirection: 'column' as const, gap: 12 },
    reviewerPickupHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', gap: 16 },
    reviewerPickupTitle: { margin: 0, fontSize: 13, fontFamily: 'var(--font-mono)', color: 'var(--text-primary)', textTransform: 'uppercase' as const, letterSpacing: '0.08em' },
    reviewerPickupSub: { margin: '4px 0 0', fontSize: 12, color: 'var(--text-tertiary)' },
    reviewerRefreshBtn: { fontSize: 11, fontFamily: 'var(--font-mono)', padding: '6px 12px', borderRadius: 4, border: '1px solid var(--border)', background: 'var(--bg-secondary)', color: 'var(--text-secondary)', cursor: 'pointer', fontWeight: 700 },
    reviewerFilters: { display: 'grid', gridTemplateColumns: 'minmax(160px, 220px) minmax(220px, 1fr)', gap: 10 },
    reviewerFilterLabel: { display: 'flex', flexDirection: 'column' as const, gap: 5, fontSize: 10, fontFamily: 'var(--font-mono)', textTransform: 'uppercase' as const, letterSpacing: '0.06em', color: 'var(--text-tertiary)' },
    reviewerFilterInput: { minWidth: 0, padding: '8px 10px', borderRadius: 4, border: '1px solid var(--border)', background: 'var(--bg-secondary)', color: 'var(--text-primary)', fontSize: 12, fontFamily: 'var(--font-mono)', letterSpacing: 0, outline: 'none' },
    reviewerPickupBanner: { margin: 0, fontSize: 12, fontFamily: 'var(--font-mono)', fontWeight: 700 },
    reviewerPrList: { display: 'flex', flexDirection: 'column' as const, gap: 8 },
    reviewerPrRow: { display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) minmax(180px, 260px) minmax(200px, 300px)', alignItems: 'start', gap: 12, padding: '10px 12px', borderRadius: 4, border: '1px solid var(--border)', background: 'var(--bg-secondary)' },
    reviewerPrMain: { display: 'flex', alignItems: 'center', gap: 8, minWidth: 0 },
    reviewerPrId: { fontSize: 11, fontFamily: 'var(--font-mono)', color: 'var(--warning)', fontWeight: 800, flexShrink: 0, textDecoration: 'none', cursor: 'pointer' },
    reviewerPrTitle: { fontSize: 13, color: 'var(--text-primary)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const, minWidth: 0, textDecoration: 'none' },
    reviewerPrStory: { fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--accent)', background: 'var(--accent-dim)', padding: '2px 6px', borderRadius: 4, flexShrink: 0 },
    reviewerPrMeta: { display: 'flex', flexDirection: 'column' as const, gap: 2, minWidth: 0, fontSize: 11, fontFamily: 'var(--font-mono)', color: 'var(--text-tertiary)' },
    reviewerPrBranch: { display: 'block', minWidth: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const },
    reviewerPrCommentCount: { fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)', marginTop: 2 },
    reviewerPickBtn: { fontSize: 11, fontFamily: 'var(--font-mono)', padding: '7px 12px', borderRadius: 4, border: '1px solid var(--warning)', background: 'rgba(245, 158, 11, 0.14)', color: 'var(--warning)', cursor: 'pointer', fontWeight: 800, letterSpacing: 0 },
    reviewerPickExcluded: { fontSize: 11, fontFamily: 'var(--font-mono)', color: 'var(--text-tertiary)', fontStyle: 'italic' as const, padding: '6px 0' },
    reviewerPrActions: { display: 'flex', flexDirection: 'column' as const, alignItems: 'flex-end', gap: 8, minWidth: 0 },
    reviewerPrActionRow: { display: 'flex', flexWrap: 'wrap' as const, gap: 8, justifyContent: 'flex-end' },
    reviewerTextBtn: { fontSize: 11, fontFamily: 'var(--font-mono)', padding: 0, border: 'none', background: 'none', color: 'var(--accent)', cursor: 'pointer', fontWeight: 700, textDecoration: 'underline', textUnderlineOffset: 2 },
    reviewerDeskBadgePending: { fontSize: 11, fontFamily: 'var(--font-mono)', padding: '7px 12px', borderRadius: 4, border: '1px solid var(--text-tertiary)', background: 'rgba(156, 163, 175, 0.12)', color: 'var(--text-secondary)', cursor: 'default', fontWeight: 800, letterSpacing: 0, userSelect: 'none' as const, textAlign: 'right' as const },
    reviewerDeskBadgeWorking: { fontSize: 11, fontFamily: 'var(--font-mono)', padding: '7px 12px', borderRadius: 4, border: '1px solid var(--warning)', background: 'rgba(245, 158, 11, 0.14)', color: 'var(--warning)', cursor: 'default', fontWeight: 800, letterSpacing: 0, userSelect: 'none' as const, textAlign: 'right' as const },
    reviewerDeskBadgeChanges: { fontSize: 11, fontFamily: 'var(--font-mono)', padding: '7px 12px', borderRadius: 4, border: '1px solid var(--error)', background: 'rgba(239, 68, 68, 0.12)', color: 'var(--error)', cursor: 'default', fontWeight: 800, letterSpacing: 0, userSelect: 'none' as const, textAlign: 'right' as const },
    reviewerDeskBadgeAwaiting: { fontSize: 11, fontFamily: 'var(--font-mono)', padding: '7px 12px', borderRadius: 4, border: '1px solid var(--warning)', background: 'rgba(245, 158, 11, 0.1)', color: 'var(--warning)', cursor: 'default', fontWeight: 800, letterSpacing: 0, userSelect: 'none' as const, textAlign: 'right' as const },
    reviewerDeskBadgeApproved: { fontSize: 11, fontFamily: 'var(--font-mono)', padding: '7px 12px', borderRadius: 4, border: '1px solid var(--success)', background: 'rgba(34, 197, 94, 0.14)', color: 'var(--success)', cursor: 'default', fontWeight: 800, letterSpacing: 0, userSelect: 'none' as const, textAlign: 'right' as const },
    reviewerFeedbackBackdrop: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.55)', zIndex: 10000, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24 },
    reviewerFeedbackPanel: { width: 'min(640px, 100%)', maxHeight: 'min(80vh, 720px)', overflow: 'hidden', display: 'flex', flexDirection: 'column' as const, background: 'var(--bg-card)', borderRadius: 8, border: '1px solid var(--border)', boxShadow: '0 12px 40px rgba(0,0,0,0.35)' },
    reviewerFeedbackHeader: { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, padding: '14px 16px', borderBottom: '1px solid var(--border)', flexShrink: 0 },
    reviewerFeedbackTitle: { margin: 0, fontSize: 15, fontFamily: 'var(--font-mono)', color: 'var(--text-primary)', display: 'flex', flexDirection: 'column' as const, gap: 4 },
    reviewerFeedbackTitleSub: { fontSize: 12, fontWeight: 400, color: 'var(--text-secondary)', lineHeight: 1.35 },
    reviewerFeedbackClose: { fontSize: 11, fontFamily: 'var(--font-mono)', padding: '6px 12px', borderRadius: 4, border: '1px solid var(--border)', background: 'var(--bg-secondary)', color: 'var(--text-secondary)', cursor: 'pointer', fontWeight: 700, flexShrink: 0 },
    reviewerFeedbackHint: { margin: 0, padding: '10px 16px 0', fontSize: 11, color: 'var(--text-tertiary)', lineHeight: 1.4 },
    reviewerFeedbackList: { padding: 12, overflowY: 'auto' as const, display: 'flex', flexDirection: 'column' as const, gap: 10 },
    reviewerFeedbackThread: { padding: 10, borderRadius: 6, border: '1px solid var(--border)', background: 'var(--bg-secondary)' },
    reviewerFeedbackThreadMeta: { display: 'flex', flexWrap: 'wrap' as const, gap: 8, marginBottom: 8 },
    reviewerFeedbackFile: { fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--accent)' },
    reviewerFeedbackCat: { fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--text-tertiary)', textTransform: 'uppercase' as const },
    reviewerFeedbackBody: { margin: 0, fontSize: 13, color: 'var(--text-primary)', lineHeight: 1.45, whiteSpace: 'pre-wrap' as const },

    taskPillList: { display: 'flex', flexDirection: 'column', gap: 4 },
    taskPill: {
        display: 'flex', alignItems: 'center', gap: 8, padding: '7px 12px',
        borderRadius: 6, border: '1.5px solid', fontSize: 12, fontFamily: 'inherit',
        color: 'var(--text-primary)',
        transition: 'all 0.15s',
        width: '100%', textAlign: 'left' as const,
    },
    requestPill: {
        borderLeftWidth: 4,
    },
    pillStatusDot: { width: 7, height: 7, borderRadius: '50%', flexShrink: 0 },
    pillId: { fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-tertiary)', flexShrink: 0, minWidth: 50 },
    pillName: { overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const, flex: 1, minWidth: 0, fontSize: 12, color: 'var(--text-primary)' },
    pillCategory: {
        fontSize: 9, fontFamily: 'var(--font-mono)', fontWeight: 700, textTransform: 'uppercase' as const,
        letterSpacing: '0.06em', padding: '2px 7px', borderRadius: 8, flexShrink: 0,
    },
    pillHours: { fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-tertiary)', flexShrink: 0 },
    requestSeverity: {
        fontSize: 9,
        fontFamily: 'var(--font-mono)',
        fontWeight: 700,
        textTransform: 'uppercase' as const,
        letterSpacing: '0.06em',
        padding: '2px 7px',
        borderRadius: 8,
        color: '#92400e',
        background: 'rgba(251, 191, 36, 0.18)',
        flexShrink: 0,
    },
    requestLocation: {
        fontFamily: 'var(--font-mono)',
        fontSize: 10,
        color: 'var(--text-tertiary)',
        flexShrink: 1,
        minWidth: 0,
        maxWidth: 160,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap' as const,
    },
    dismissBtn: {
        marginLeft: 2, cursor: 'pointer', fontSize: 14, lineHeight: 1, color: 'var(--text-tertiary)',
        padding: '0 2px', borderRadius: 4, transition: 'color 0.15s, background 0.15s',
        fontWeight: 700, flexShrink: 0,
    } as CSSProperties,
    selectActions: { display: 'flex', alignItems: 'center', gap: 8, marginBottom: 10 },
    selectActionBtn: {
        fontSize: 11, fontFamily: 'var(--font-mono)', padding: '3px 10px', borderRadius: 4,
        background: 'var(--bg-secondary)', border: '1px solid var(--border)', color: 'var(--text-secondary)',
        cursor: 'pointer', fontWeight: 600,
    },
    selectedCount: { fontSize: 11, fontFamily: 'var(--font-mono)', color: 'var(--accent)', fontWeight: 600 },

    prCardList: { display: 'flex', flexDirection: 'column', gap: 6 },
    prCard: {
        display: 'flex', alignItems: 'stretch', gap: 10, padding: '8px 12px',
        borderRadius: 6, border: '1.5px solid var(--border)', background: 'var(--bg-secondary)',
        textDecoration: 'none', color: 'inherit', cursor: 'pointer', transition: 'border-color 0.15s, box-shadow 0.15s',
    },
    prCardDot: { width: 7, height: 7, borderRadius: '50%', flexShrink: 0, marginTop: 6 },
    prCardBody: { flex: 1, minWidth: 0, display: 'flex', flexDirection: 'column' as const, gap: 4 },
    prCardTop: { display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' as const },
    prCardId: { fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-tertiary)', fontWeight: 700 },
    prStatusBadge: {
        fontSize: 9, fontFamily: 'var(--font-mono)', fontWeight: 700, textTransform: 'uppercase' as const,
        letterSpacing: '0.06em', padding: '2px 8px', borderRadius: 8, border: '1px solid', flexShrink: 0,
    },
    prCardTitle: { fontSize: 13, fontWeight: 600, color: 'var(--text-primary)', lineHeight: 1.35, display: '-webkit-box' as const, WebkitLineClamp: 2, WebkitBoxOrient: 'vertical' as const, overflow: 'hidden' },
    prCardMeta: { display: 'flex', flexWrap: 'wrap' as const, gap: 6, alignItems: 'center' },
    prMetaPill: {
        fontSize: 10, fontFamily: 'var(--font-mono)', color: 'var(--text-secondary)',
        padding: '2px 8px', borderRadius: 8, background: 'var(--bg-primary)', border: '1px solid var(--border)',
    },
    prCardLink: { flexShrink: 0, fontSize: 14, color: 'var(--text-tertiary)', alignSelf: 'center', fontWeight: 700 },

    cypressStats: { display: 'flex', gap: 16, marginBottom: 12 },
    cypressLabel: { fontSize: 10, color: 'var(--text-tertiary)', textTransform: 'uppercase', fontFamily: 'var(--font-mono)' },
    failureList: { display: 'flex', flexDirection: 'column', gap: 8 },
    failureItem: { display: 'flex', flexDirection: 'column', gap: 2, padding: 8, background: 'rgba(248, 113, 113, 0.05)', borderRadius: 4, borderLeft: '2px solid var(--error)' },
    failureSpec: { fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--text-tertiary)' },
    failureTest: { fontSize: 12, color: 'var(--text-primary)' },
    failureError: { fontFamily: 'var(--font-mono)', fontSize: 11, color: 'var(--error)', whiteSpace: 'pre-wrap', wordBreak: 'break-word' },

    testRunList: { display: 'flex', flexDirection: 'column', gap: 4, maxHeight: 400, overflowY: 'auto' },
    testRunRow: { borderRadius: 4, border: '1px solid var(--border)', overflow: 'hidden' },
    testRunHeader: {
        display: 'flex', alignItems: 'center', gap: 8, width: '100%',
        padding: '8px 10px', background: 'var(--bg-secondary)', border: 'none',
        cursor: 'pointer', color: 'inherit', fontFamily: 'inherit', fontSize: 12, textAlign: 'left' as const,
    },
    testRunStatus: { fontSize: 14, fontWeight: 700, flexShrink: 0, width: 16, textAlign: 'center' as const },
    testRunSpec: { flex: 1, fontFamily: 'var(--font-mono)', fontSize: 11, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const },
    testRunCounts: { fontFamily: 'var(--font-mono)', fontSize: 11, fontWeight: 600, flexShrink: 0 },
    testRunTime: { fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-tertiary)', flexShrink: 0 },
    testRunDetails: { padding: '8px 10px', background: 'var(--bg-card)', borderTop: '1px solid var(--border)' },
    testRunMeta: { display: 'flex', gap: 16, fontSize: 11, fontFamily: 'var(--font-mono)', color: 'var(--text-tertiary)', marginBottom: 8 },

    eventList: { display: 'flex', flexDirection: 'column', gap: 4, maxHeight: 300, overflowY: 'auto' },
    eventRow: {
        display: 'flex', alignItems: 'flex-start', gap: 8, fontSize: 12,
        padding: '6px 8px 6px 10px', borderRadius: 6, background: 'var(--bg-secondary)',
        borderLeft: '3px solid', borderTop: '1px solid var(--border)', borderRight: '1px solid var(--border)', borderBottom: '1px solid var(--border)',
    },
    eventGlyph: { fontSize: 12, lineHeight: 1, flexShrink: 0, width: 14, textAlign: 'center' as const, marginTop: 2, fontWeight: 700 },
    eventTime: { fontFamily: 'var(--font-mono)', fontSize: 10, color: 'var(--text-tertiary)', flexShrink: 0, minWidth: 56, paddingTop: 2 },
    eventMessage: { color: 'var(--text-secondary)', lineHeight: 1.45, flex: 1, minWidth: 0 },

    stepModeGroup: { display: 'flex', alignItems: 'center', gap: 8 },
    stepToggleLabel: { display: 'flex', alignItems: 'center', gap: 6, cursor: 'pointer' },
    stepToggleLabelText: { fontSize: 11, fontFamily: 'var(--font-mono)', color: 'var(--text-tertiary)', textTransform: 'uppercase' as const, letterSpacing: '0.06em' },
    stepToggleTrack: { width: 34, height: 18, borderRadius: 9, border: '1px solid var(--border)', cursor: 'pointer', position: 'relative' as const, display: 'flex', alignItems: 'center', padding: 0, transition: 'background 0.15s' },
    stepToggleThumb: { width: 14, height: 14, borderRadius: '50%', background: '#fff', transition: 'transform 0.15s', boxShadow: '0 1px 3px rgba(0,0,0,0.3)' },
    nextStepBtn: { fontSize: 12, fontFamily: 'var(--font-mono)', fontWeight: 700, padding: '5px 14px', borderRadius: 4, background: 'var(--accent)', border: 'none', color: '#fff', cursor: 'pointer', letterSpacing: '0.03em', animation: 'pulse 1.5s ease-in-out infinite' },

    contextActionBar: {
        padding: '16px 18px',
        borderRadius: 8,
        border: '1px solid var(--border)',
        background: 'var(--bg-card)',
        boxShadow: '0 2px 12px rgba(0, 0, 0, 0.08)',
        display: 'flex',
        flexDirection: 'column' as const,
        gap: 14,
    },
    contextActionBarTitleRow: { display: 'flex', flexDirection: 'column' as const, gap: 6 },
    contextActionBarKicker: {
        fontSize: 10,
        fontFamily: 'var(--font-mono)',
        textTransform: 'uppercase' as const,
        letterSpacing: '0.08em',
        color: 'var(--accent)',
        fontWeight: 700,
    },
    contextActionBarHeading: {
        margin: 0,
        fontSize: 16,
        fontWeight: 700,
        color: 'var(--text-primary)',
        lineHeight: 1.35,
    },
    contextActionBarButtons: {
        display: 'flex',
        flexWrap: 'wrap' as const,
        gap: 10,
        alignItems: 'center',
    },
    contextActionBtnPrimary: {
        fontSize: 12,
        fontFamily: 'var(--font-mono)',
        fontWeight: 700,
        padding: '8px 16px',
        borderRadius: 6,
        border: '1px solid var(--success)',
        background: 'var(--success)',
        color: '#fff',
        letterSpacing: '0.03em',
    },
    contextActionBtnSecondary: {
        fontSize: 12,
        fontFamily: 'var(--font-mono)',
        fontWeight: 700,
        padding: '8px 16px',
        borderRadius: 6,
        border: '1px solid var(--info)',
        background: 'rgba(6, 182, 212, 0.12)',
        color: 'var(--info)',
        letterSpacing: '0.03em',
    },
    contextActionBtnWarning: {
        fontSize: 12,
        fontFamily: 'var(--font-mono)',
        fontWeight: 700,
        padding: '8px 16px',
        borderRadius: 6,
        border: '1px solid #f59e0b',
        background: '#f59e0b',
        color: '#111827',
        letterSpacing: '0.03em',
    },
    contextActionBtnTertiary: {
        fontSize: 12,
        fontFamily: 'var(--font-mono)',
        fontWeight: 600,
        padding: '8px 16px',
        borderRadius: 6,
        border: '1px solid var(--border)',
        background: 'var(--bg-secondary)',
        color: 'var(--text-secondary)',
        letterSpacing: '0.03em',
    },
    contextActionBarHint: {
        margin: 0,
        fontSize: 11,
        color: 'var(--text-tertiary)',
        fontFamily: 'var(--font-mono)',
        lineHeight: 1.5,
    },
    contextActionBarBanner: {
        margin: 0,
        fontSize: 12,
        fontFamily: 'var(--font-mono)',
        lineHeight: 1.45,
        fontWeight: 600,
    },
};
