import type { CSSProperties } from 'react';

export const agentCardStyles: Record<string, CSSProperties> = {
    card: {
        background: 'var(--bg-card)',
        border: '1px solid var(--border)',
        borderRadius: 8,
        padding: 20,
        boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
        display: 'flex',
        flexDirection: 'column' as const,
        gap: 10,
        cursor: 'pointer',
        transition: 'background 0.15s, box-shadow 0.15s, border-color 0.15s',
        outline: 'none',
    },
    cardHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        gap: 12,
    },
    cardHeaderLeft: {
        display: 'flex',
        gap: 10,
        alignItems: 'center',
    },
    cardAvatar: {
        width: 40,
        height: 40,
        borderRadius: '50%',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 18,
        fontWeight: 700,
        color: '#fff',
        flexShrink: 0,
    },
    cardName: {
        fontSize: 16,
        fontWeight: 600,
        color: 'var(--text-primary)',
        lineHeight: 1.3,
    },
    cardRole: {
        fontSize: 11,
        fontWeight: 500,
        color: 'var(--text-tertiary)',
        fontFamily: 'var(--font-mono)',
    },
    cardBadges: {
        display: 'flex',
        flexDirection: 'column' as const,
        alignItems: 'flex-end',
        gap: 4,
    },
    phaseBadge: {
        fontSize: 12,
        fontWeight: 600,
        fontFamily: 'var(--font-mono)',
        display: 'flex',
        alignItems: 'center',
        gap: 6,
    },
    statusDot: {
        width: 8,
        height: 8,
        borderRadius: '50%',
        display: 'inline-block',
    },
    storyBadge: {
        fontSize: 12,
        fontWeight: 600,
        fontFamily: 'var(--font-mono)',
        color: 'var(--accent)',
    },
    taskRow: {
        fontSize: 12,
        fontWeight: 400,
        fontFamily: 'var(--font-mono)',
        color: 'var(--text-secondary)',
        lineHeight: 1.3,
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap' as const,
        borderTop: '1px solid var(--border)',
        paddingTop: 10,
    },
    cardActions: {
        display: 'flex',
        gap: 8,
        paddingTop: 10,
        borderTop: '1px solid var(--border)',
    },
    actionBtn: {
        padding: '6px 14px',
        borderRadius: 6,
        border: '1px solid var(--border)',
        background: 'var(--bg-card)',
        color: 'var(--text-secondary)',
        fontSize: 12,
        fontWeight: 600,
        fontFamily: 'var(--font-mono)',
        cursor: 'pointer',
        transition: 'background 0.15s',
    },
    actionBtnPrimary: {
        background: 'var(--accent)',
        color: '#fff',
        borderColor: 'var(--accent)',
    },
    actionBtnWarn: {
        background: 'var(--warning)',
        color: '#212529',
        borderColor: 'var(--warning)',
    },
    actionBtnPaused: {
        background: '#f59e0b',
        color: '#212529',
        borderColor: '#f59e0b',
        fontWeight: 700,
    },
    pausedBadge: {
        fontSize: 10,
        fontWeight: 700,
        fontFamily: 'var(--font-mono)',
        textTransform: 'uppercase' as const,
        color: '#f59e0b',
        background: 'rgba(245,158,11,0.12)',
        padding: '2px 6px',
        borderRadius: 4,
        letterSpacing: 0.5,
        animation: 'pausePulse 2s ease-in-out infinite',
    },
    modelRow: {
        position: 'relative' as const,
        paddingTop: 8,
    },
    modelPill: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: 6,
        padding: '4px 10px',
        borderRadius: 20,
        border: '1px solid var(--border)',
        background: 'var(--bg-card)',
        fontSize: 11,
        fontWeight: 600,
        fontFamily: 'var(--font-mono)',
        cursor: 'pointer',
        transition: 'all 0.15s',
        outline: 'none',
    },
    modelPopup: {
        position: 'absolute' as const,
        top: '100%',
        left: 0,
        marginTop: 6,
        minWidth: 260,
        maxHeight: 400,
        overflowY: 'auto' as const,
        background: 'var(--bg-card)',
        border: '1px solid var(--border)',
        borderRadius: 10,
        boxShadow: '0 8px 24px rgba(0,0,0,0.25)',
        zIndex: 100,
        padding: '6px 0',
    },
    modelSearch: {
        width: '100%',
        padding: '6px 10px',
        border: '1px solid var(--border)',
        borderRadius: 6,
        background: 'var(--bg-page)',
        color: 'var(--text-primary)',
        fontSize: 12,
        fontFamily: 'var(--font-mono)',
        outline: 'none',
        boxSizing: 'border-box' as const,
    },
    modelPopupArrow: {
        position: 'absolute' as const,
        top: -5,
        left: 16,
        width: 10,
        height: 10,
        background: 'var(--bg-card)',
        border: '1px solid var(--border)',
        borderRight: 'none',
        borderBottom: 'none',
        transform: 'rotate(45deg)',
    },
    modelCatHeader: {
        fontSize: 10,
        fontWeight: 700,
        fontFamily: 'var(--font-mono)',
        color: 'var(--text-secondary)',
        textTransform: 'uppercase' as const,
        letterSpacing: 1,
        padding: '8px 14px 4px',
    },
    modelOption: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        width: '100%',
        padding: '6px 14px',
        border: 'none',
        background: 'transparent',
        color: 'var(--text-primary)',
        fontSize: 12,
        fontFamily: 'var(--font-mono)',
        cursor: 'pointer',
        textAlign: 'left' as const,
        transition: 'background 0.1s',
    },
    modelOptionActive: {
        background: 'rgba(99,102,241,0.12)',
        fontWeight: 700,
    },
    modelManageRow: {
        borderTop: '1px solid var(--border)',
        marginTop: 4,
        padding: '6px 10px 4px',
    },
    modelManageHint: {
        display: 'block',
        textAlign: 'center' as const,
        fontSize: 10,
        color: 'var(--text-secondary)',
        fontFamily: 'var(--font-mono)',
        opacity: 0.7,
        padding: '2px 0',
    },
};
