import type { CSSProperties } from 'react';

export const createStoryModalStyles: Record<string, CSSProperties> = {
    modal: {
        position: 'fixed',
        inset: 0,
        background: 'rgba(0,0,0,0.5)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 9998,
    },
    modalContent: {
        background: 'var(--bg-card)',
        border: '1px solid var(--border)',
        borderRadius: 10,
        padding: '20px 24px',
        width: 420,
        maxWidth: '90vw',
        boxShadow: '0 8px 32px rgba(0,0,0,0.2)',
    },
    modalClose: {
        background: 'none',
        border: 'none',
        fontSize: 20,
        color: 'var(--text-tertiary)',
        cursor: 'pointer',
        padding: '0 4px',
    },
    formLabel: {
        display: 'block',
        fontSize: 12,
        fontFamily: 'var(--font-mono)',
        color: 'var(--text-tertiary)',
        textTransform: 'uppercase' as const,
        letterSpacing: '0.06em',
        marginBottom: 4,
    },
    formInput: {
        width: '100%',
        padding: '8px 10px',
        fontSize: 13,
        fontFamily: 'var(--font-sans)',
        color: 'var(--text-primary)',
        background: 'var(--bg-secondary)',
        border: '1px solid var(--border)',
        borderRadius: 4,
        outline: 'none',
        boxSizing: 'border-box' as const,
    },
    cancelBtn: {
        padding: '6px 14px',
        borderRadius: 6,
        border: '1px solid var(--border)',
        background: 'var(--bg-card)',
        color: 'var(--text-secondary)',
        fontSize: 12,
        fontWeight: 600,
        fontFamily: 'var(--font-mono)',
        cursor: 'pointer',
    },
    createStoryBtn: {
        padding: '6px 14px',
        borderRadius: 6,
        border: '1px solid var(--accent)',
        background: 'var(--accent)',
        color: '#fff',
        fontSize: 12,
        fontWeight: 600,
        fontFamily: 'var(--font-mono)',
        cursor: 'pointer',
    },
};
