import type { CSSProperties } from 'react';

export const floorStatsBarStyles: Record<string, CSSProperties> = {
    statsBar: {
        display: 'flex',
        flexWrap: 'wrap' as const,
        gap: 12,
        padding: '16px 0',
        justifyContent: 'center',
        alignItems: 'stretch',
    },
    testBreakdownPopup: {
        position: 'absolute' as const,
        top: '100%',
        left: '50%',
        transform: 'translateX(-50%)',
        marginTop: 6,
        minWidth: 320,
        maxHeight: 360,
        overflowY: 'auto' as const,
        background: 'var(--bg-card)',
        border: '1px solid var(--border)',
        borderRadius: 8,
        boxShadow: '0 8px 24px rgba(0,0,0,0.15)',
        zIndex: 100,
        padding: '6px 0',
    },
    testBreakdownHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        padding: '4px 12px 6px',
        fontSize: 10,
        fontFamily: 'var(--font-mono)',
        color: 'var(--text-tertiary)',
        textTransform: 'uppercase' as const,
        letterSpacing: '0.08em',
        borderBottom: '1px solid var(--border)',
    },
    testBreakdownRow: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        padding: '6px 12px',
        borderLeft: '3px solid',
        fontSize: 12,
        fontFamily: 'var(--font-mono)',
    },
    testBreakdownSpec: {
        flex: 1,
        fontSize: 11,
        overflow: 'hidden' as const,
        textOverflow: 'ellipsis' as const,
        whiteSpace: 'nowrap' as const,
        color: 'var(--text-primary)',
    },
    testBreakdownResult: {
        flexShrink: 0,
        fontSize: 12,
    },
    testBreakdownTime: {
        flexShrink: 0,
        fontSize: 10,
        color: 'var(--text-tertiary)',
        minWidth: 50,
        textAlign: 'right' as const,
    },
};
