#!/usr/bin/env python3
"""
auto-pr.py  —  Automatic PR creation from meeting-triggered pipeline runs.

Watches .meeting-tasks.jsonl for tasks that have been executed, then:
  1. Detects the resulting git diff
  2. Creates a GitHub PR via `gh pr create`
  3. Posts the PR link back to the Teams meeting bot

This is the last step in the "conversation → PR" loop:
  meeting → whisper-stream → bridge → fix-pipeline → [auto-pr] → Teams chat

Usage:
  python scripts/auto-pr.py serve --bot-url http://localhost:3978
  python scripts/auto-pr.py create --task "Fix null ref in userService" --branch fix/null-ref-userservice
  python scripts/auto-pr.py status
"""

import argparse
import json
import re
import subprocess
import sys
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

SCRIPTS_DIR   = Path(__file__).parent
TASKS_LOG     = Path(".meeting-tasks.jsonl")
PR_LOG        = Path(".auto-pr.jsonl")
POLL_INTERVAL = 10   # seconds between checks for new completed tasks
BASE_BRANCH   = "main"


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _load_tasks() -> list[dict]:
    if not TASKS_LOG.exists():
        return []
    records = []
    with TASKS_LOG.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    records.append(json.loads(line))
                except Exception:
                    pass
    return records


def _load_pr_log() -> list[dict]:
    if not PR_LOG.exists():
        return []
    records = []
    with PR_LOG.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    records.append(json.loads(line))
                except Exception:
                    pass
    return records


def _append_pr(record: dict) -> None:
    with PR_LOG.open("a", encoding="utf-8") as f:
        f.write(json.dumps(record, ensure_ascii=False) + "\n")


# ─── Git helpers ──────────────────────────────────────────────────────────────

def _run(cmd: list[str], timeout: int = 30) -> tuple[int, str, str]:
    result = subprocess.run(
        cmd, capture_output=True, text=True,
        encoding="utf-8", errors="replace", timeout=timeout,
    )
    return result.returncode, result.stdout.strip(), result.stderr.strip()


def get_current_branch() -> str:
    _, out, _ = _run(["git", "rev-parse", "--abbrev-ref", "HEAD"])
    return out or "main"


def has_uncommitted_changes() -> bool:
    rc, out, _ = _run(["git", "status", "--porcelain"])
    return rc == 0 and bool(out.strip())


def get_diff_stat() -> str:
    _, out, _ = _run(["git", "diff", "--stat", f"{BASE_BRANCH}...HEAD"])
    return out


def commit_and_push(branch: str, message: str) -> bool:
    """Stage all changes, commit, and push to the feature branch."""
    # Checkout or create branch
    rc, _, _ = _run(["git", "checkout", "-b", branch])
    if rc != 0:
        # Branch already exists — switch to it
        _run(["git", "checkout", branch])

    # Stage and commit
    rc, _, err = _run(["git", "add", "-A"])
    if rc != 0:
        print(f"  [auto-pr] git add failed: {err}")
        return False

    rc, _, err = _run(["git", "commit", "-m", message], timeout=30)
    if rc != 0:
        if "nothing to commit" in err:
            print("  [auto-pr] nothing to commit")
            return False
        print(f"  [auto-pr] commit failed: {err}")
        return False

    rc, _, err = _run(["git", "push", "-u", "origin", branch], timeout=60)
    if rc != 0:
        print(f"  [auto-pr] push failed: {err}")
        return False

    return True


# ─── PR creation ──────────────────────────────────────────────────────────────

def slugify(text: str, max_len: int = 40) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return slug[:max_len].strip("-")


def make_branch_name(task: str, cluster: str) -> str:
    ts   = datetime.now(timezone.utc).strftime("%m%d%H%M")
    slug = slugify(task)
    return f"meeting/{cluster}/{slug}-{ts}"


def create_pr(task: str, branch: str, cluster: str, meeting_id: str,
              speaker: str, diff_stat: str) -> dict | None:
    """Create a GitHub PR via the gh CLI. Returns PR info dict or None."""
    title = f"[Meeting] {task[:70]}"
    body  = f"""\
## Source
Automatically generated from meeting conversation.

**Detected by**: SDLC Framework meeting agent
**Speaker**: {speaker}
**Meeting**: `{meeting_id}`
**Cluster**: `{cluster}`

## Changes
```
{diff_stat or "(no diff stat available)"}
```

## Review notes
This PR was generated automatically. Please review the diff before merging.

---
🤖 Generated by [SDLC Framework meeting agent](https://github.com/SDLC Framework)
"""
    rc, out, err = _run(
        ["gh", "pr", "create",
         "--title", title,
         "--body",  body,
         "--base",  BASE_BRANCH,
         "--head",  branch],
        timeout=60,
    )
    if rc != 0:
        print(f"  [auto-pr] gh pr create failed: {err}")
        return None

    # Parse PR URL from output
    url_match = re.search(r"https://github\.com/[^\s]+", out)
    pr_url = url_match.group(0) if url_match else out.strip()

    return {"url": pr_url, "title": title, "branch": branch}


# ─── Teams notification ───────────────────────────────────────────────────────

def notify_teams_bot(bot_url: str, meeting_id: str, task: str, pr_url: str) -> bool:
    """POST a notification to the Teams bot so it can message the meeting."""
    payload = json.dumps({
        "type":       "pr_created",
        "task":       task,
        "pr_url":     pr_url,
        "meeting_id": meeting_id,
        "ts":         _now(),
    }).encode()
    try:
        req = urllib.request.Request(
            f"{bot_url}/notify",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=5):
            return True
    except Exception as e:
        print(f"  [auto-pr] Teams notify failed (non-fatal): {e}")
        return False


# ─── Watch loop ───────────────────────────────────────────────────────────────

def watch_and_create(bot_url: str) -> None:
    """
    Poll .meeting-tasks.jsonl for newly executed tasks.
    For each executed task that doesn't have a PR yet, create one.
    """
    created_tasks: set[str] = {r.get("task", "") for r in _load_pr_log()}
    print(f"Watching for completed pipeline tasks (poll every {POLL_INTERVAL}s)...")
    print(f"Bot URL: {bot_url}")

    while True:
        try:
            tasks = _load_tasks()
            for task_rec in tasks:
                task = task_rec.get("task", "")
                if not task or task in created_tasks:
                    continue

                # Only process tasks that went to the pipeline (high confidence)
                if task_rec.get("confidence", 0) < 0.70:
                    continue

                # Check if there are changes to push
                if not has_uncommitted_changes():
                    continue

                cluster    = task_rec.get("cluster", "other")
                meeting_id = task_rec.get("meeting_id", "unknown")
                speaker    = task_rec.get("speaker", "unknown")
                branch     = make_branch_name(task, cluster)
                msg        = f"fix({cluster}): {task[:72]}\n\nAuto-generated from meeting. Source: {meeting_id}"
                diff_stat  = get_diff_stat()

                print(f"\n[auto-pr] Creating PR for: {task[:60]}")

                if commit_and_push(branch, msg):
                    pr = create_pr(task, branch, cluster, meeting_id, speaker, diff_stat)
                    if pr:
                        print(f"  PR created: {pr['url']}")
                        notify_teams_bot(bot_url, meeting_id, task, pr["url"])
                        _append_pr({
                            "task":       task,
                            "cluster":    cluster,
                            "meeting_id": meeting_id,
                            "branch":     branch,
                            "pr_url":     pr["url"],
                            "ts":         _now(),
                        })
                        created_tasks.add(task)
                else:
                    print(f"  Nothing to commit for: {task[:50]}")
                    created_tasks.add(task)  # don't retry

        except KeyboardInterrupt:
            print("\nStopped.")
            return
        except Exception as e:
            print(f"[auto-pr] error: {e}")

        time.sleep(POLL_INTERVAL)


# ─── CLI ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Auto-PR: turn meeting pipeline outputs into GitHub PRs"
    )
    sub = parser.add_subparsers(dest="cmd", required=True)

    srv = sub.add_parser("serve", help="Watch for completed tasks and create PRs")
    srv.add_argument("--bot-url",     default="http://localhost:3978",
                     help="Teams bot URL for PR link notifications")
    srv.add_argument("--base-branch", default="main")
    srv.add_argument("--interval",    type=int, default=POLL_INTERVAL)

    cr = sub.add_parser("create", help="Manually create a PR for current git state")
    cr.add_argument("--task",    required=True)
    cr.add_argument("--cluster", default="other")
    cr.add_argument("--branch",  default="")
    cr.add_argument("--speaker", default="manual")
    cr.add_argument("--meeting-id", default="manual")

    sub.add_parser("status", help="Show PR creation log")

    args = parser.parse_args()

    if args.cmd == "serve":
        global BASE_BRANCH, POLL_INTERVAL
        BASE_BRANCH   = args.base_branch
        POLL_INTERVAL = args.interval
        watch_and_create(args.bot_url)

    elif args.cmd == "create":
        branch    = args.branch or make_branch_name(args.task, args.cluster)
        diff_stat = get_diff_stat()
        msg       = f"fix({args.cluster}): {args.task[:72]}\n\nManual PR creation."

        if not has_uncommitted_changes():
            print("No uncommitted changes to push.")
            sys.exit(1)

        if commit_and_push(branch, msg):
            pr = create_pr(args.task, branch, args.cluster, args.meeting_id,
                           args.speaker, diff_stat)
            if pr:
                print(f"PR created: {pr['url']}")
            else:
                print("PR creation failed — check gh CLI auth")
                sys.exit(1)
        else:
            print("Commit/push failed")
            sys.exit(1)

    elif args.cmd == "status":
        prs = _load_pr_log()
        if not prs:
            print("No PRs created yet")
            return
        print(f"PRs created from meeting agent: {len(prs)}")
        print()
        for pr in prs[-10:]:
            print(f"  {pr.get('ts', '')[:19]}  [{pr.get('cluster', '?')}]  "
                  f"{pr.get('task', '')[:50]}")
            print(f"    {pr.get('pr_url', '?')}")


if __name__ == "__main__":
    main()
